#! /usr/bin/env bash
#
# -*- mode: shell-script -*-

case $# in
(0) dir='.';;
(1) dir=$1;;
(*) echo "usage: disk_usage <dir>"
  exit 1;;
esac

echo "Disk usage on '$dir' in MB"

du -s -m --one-file-system $dir/* $dir/.[A-Za-z0-9]* | sort -rn | head
